[SECURE]
AddressPool = 10.0.0.0/24
AllowedGroups = SECURE, SERVICE

[SERVICE]
AddressPool = 10.0.1.0/24
AllowedGroups = SECURE, SERVICE, PUBLIC, PRIVATE, GUEST

[PUBLIC]
AddressPool = 10.0.2.0/24
AllowedGroups = SERVICE, PUBLIC

[PRIVATE]
AddressPool = 10.0.3.0/24
AllowedGroups = SERVICE, PUBLIC

[GUEST]
AddressPool = 10.0.4.0/24
AllowedGroups = SERVICE